name: "deploy-py-lambda"

on:
  push:
    branches: 
      - master


jobs:
  zip_n_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Zip the Code
      uses: montudor/action-zip@v0.1.0
      with: 
        args: zip -jr ./sample_test.zip sample_test
    - name: Lambda Deploy Zip File
      uses: appleboy/lambda-action@master
      with:
       aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws_region: 'us-west-2'
       function_name: github_demo
       zip_file: sample_test.zip
